import type { HomePreset } from './homePresets';

export const SPICYBOX_PRESETS: HomePreset[] = [
  {
    id: 'spicybox-standing-backshots-slam',
    title: 'Standing Backshots Slam',
    generation: 13,
    remixes: '12.8k used',
    verified: true,
    cost: 18,
    sourceExt: '.jpg',
  },
  {
    id: 'spicybox-classic-blowjob',
    title: 'Classic Blowjob',
    generation: 14,
    remixes: '26.8k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-double-blowjob',
    title: 'Double Blowjob',
    generation: 15,
    remixes: '28.6k used',
    verified: true,
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-blowjob',
    title: 'Blowjob',
    generation: 16,
    remixes: '10.2k used',
    verified: true,
    cost: 18,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-pov-missionary',
    title: 'POV Missionary',
    generation: 17,
    remixes: '17.2k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-pov-insane-blowjob',
    title: 'POV Insane Blowjob',
    generation: 18,
    remixes: '12.9k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-wide-spread-ass',
    title: 'Wide Spread Ass',
    generation: 19,
    remixes: '29.1k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-nudify',
    title: 'Nudify',
    generation: 20,
    remixes: '28.9k used',
    cost: 18,
    sourceExt: '.jpg',
  },
  {
    id: 'spicybox-doggy-style-looking-back',
    title: 'Doggy Style Looking Back',
    generation: 21,
    remixes: '12.5k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-deep-squat-anal',
    title: 'Deep Squat Anal',
    generation: 22,
    remixes: '21k used',
    verified: true,
    cost: 18,
    hasVideo: true,
    sourceExt: '.jpg',
  },
  {
    id: 'spicybox-glory-hole-blowjob',
    title: 'Glory Hole Blowjob',
    generation: 23,
    remixes: '23.4k used',
    verified: true,
    cost: 18,
    hasVideo: true,
    sourceExt: '.jpg',
  },
  {
    id: 'spicybox-pov-cowgirl',
    title: 'POV Cowgirl',
    generation: 24,
    remixes: '26.4k used',
    verified: true,
    cost: 18,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-explosive-cumshot',
    title: 'Explosive Cumshot',
    generation: 25,
    remixes: '26k used',
    verified: true,
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-gangbang-cowgirl-blowjob',
    title: 'Gangbang Cowgirl Blowjob',
    generation: 26,
    remixes: '22.5k used',
    verified: true,
    cost: 18,
    hasVideo: true,
    sourceExt: '.jpg',
  },
  {
    id: 'spicybox-double-cowgirl',
    title: 'Double Cowgirl',
    generation: 27,
    remixes: '25.2k used',
    verified: true,
    cost: 18,
    hasVideo: true,
    sourceExt: '.jpg',
  },
  {
    id: 'spicybox-doggy-style',
    title: 'Doggy Style',
    generation: 28,
    remixes: '14.1k used',
    verified: true,
    cost: 18,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-intense-cowgirl',
    title: 'Intense Cowgirl',
    generation: 29,
    remixes: '10.9k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
  {
    id: 'spicybox-sloppy-cowgirl',
    title: 'Sloppy Cowgirl',
    generation: 30,
    remixes: '19.9k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.jpg',
  },
  {
    id: 'spicybox-missionary-stroke',
    title: 'Missionary Stroke',
    generation: 31,
    remixes: '20.7k used',
    cost: 18,
    hasVideo: true,
    sourceExt: '.webp',
  },
];
