import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import Link from 'next/link';
import SiteHeader from '../components/SiteHeader';
import { buildPageMetadata } from '@/lib/seo';

export const metadata: Metadata = buildPageMetadata({
  title: 'Cookie Policy',
  description:
    'How SLUTBOT AI uses cookies and similar technologies, including essential, performance, and analytics cookies. Contact legal@slutbot.ai with questions.',
  path: '/cookies',
});

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-black text-white">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-white/65 sm:text-base">{children}</div>
    </section>
  );
}

const Mail = ({ children = 'legal@slutbot.ai' }: { children?: string }) => (
  <a href={`mailto:${children}`} className="text-white underline underline-offset-2 hover:text-white/80">
    {children}
  </a>
);

export default function CookiesPage() {
  return (
    <div className="w-full text-white">
      <SiteHeader />

      <main className="mx-auto max-w-3xl px-4 py-10 sm:px-6 sm:py-14">
        <h1 className="text-3xl font-black tracking-tight sm:text-4xl">Cookie Policy</h1>
        <p className="mt-3 text-sm text-white/45">Last updated on: 08/24/2026</p>

        <div className="mt-10 space-y-10">
          <Section title="1. Introduction">
            <p>
              This Cookie Policy explains how cookies and similar technologies are used on the SLUTBOT AI Platform at
              Slutbot.ai (the “Platform”). By using our Platform, you consent to the use of cookies in accordance with
              this Cookie Policy.
            </p>
          </Section>

          <Section title="2. What are cookies?">
            <p>
              Cookies are small text files that are stored on your device (computer, tablet, or mobile phone) when you
              visit a website. They are widely used to make websites work more efficiently, as well as to provide
              information to the website owners.
            </p>
          </Section>

          <Section title="3. Types of cookies we use">
            <p>
              <strong className="text-white/80">3.1. Essential cookies.</strong> These cookies are necessary for the
              Platform to function properly. They enable core functionality such as page navigation and access to
              secure areas. The Platform cannot function properly without these cookies.
            </p>
            <p>
              <strong className="text-white/80">3.2. Performance cookies.</strong> These cookies collect information
              about how visitors use our Platform, such as which pages are visited most often, and whether visitors
              receive error messages from certain pages. These cookies do not collect information that identifies a
              visitor. All information these cookies collect is aggregated and therefore anonymous. It is only used to
              improve how the Platform works.
            </p>
            <p>
              <strong className="text-white/80">3.3. Functionality cookies.</strong> These cookies allow the Platform
              to remember choices you make (such as your content preferences, username, language, or the region you
              are in) and provide enhanced, more personalized features. For example, we may display different content
              based on your chosen content preferences. Cookies may also be stored so that the same warning messages
              are not displayed twice.
            </p>
          </Section>

          <Section title="4. Google Analytics">
            <p>
              We use Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics
              uses cookies to help analyze how users use the Platform. The information generated by the cookie about
              your use of the Platform (including your IP address) will be transmitted to and stored by Google on
              servers in the United States. Google will use this information for the purpose of evaluating your use of
              the Platform, compiling reports on website activity for website operators, and providing other services
              relating to website activity and internet usage. Google may also transfer this information to third
              parties where required to do so by law, or where such third parties process the information on Google’s
              behalf. Google will not associate your IP address with any other data held by Google.
            </p>
            <p>
              You may refuse the use of cookies by selecting the appropriate settings on your browser. Please note
              that if you do this you may not be able to use the full functionality of the Platform. By using the
              Platform, you consent to the processing of data about you by Google in the manner and for the purposes
              set out above.
            </p>
          </Section>

          <Section title="5. Managing cookies">
            <p>
              You can control and/or delete cookies as you wish. You can delete all cookies that are already on your
              device, and you can set most browsers to prevent them from being placed. If you do this, however, you
              may have to manually adjust some preferences every time you visit the Platform, and some services and
              functionalities may not work.
            </p>
          </Section>

          <Section title="6. Changes to this Cookie Policy">
            <p>
              We may update this Cookie Policy from time to time in order to reflect changes to the cookies we use or
              for other operational, legal, or regulatory reasons. Please revisit this Cookie Policy regularly to stay
              informed about our use of cookies and related technologies.
            </p>
          </Section>

          <Section title="7. Contact us">
            <p>
              If you have any questions about our use of cookies or this Cookie Policy, please contact us at <Mail />.
            </p>
            <p>
              Related policies:{' '}
              <Link href="/privacy" className="text-white underline underline-offset-2 hover:text-white/80">
                Privacy Policy
              </Link>
              {' '}and{' '}
              <Link href="/terms" className="text-white underline underline-offset-2 hover:text-white/80">
                Terms of Service
              </Link>
              .
            </p>
          </Section>
        </div>
      </main>
    </div>
  );
}
