/** ISO 3166-1 alpha-2 display names. Safe to copy into other apps. */
export const COUNTRY_NAMES: Record<string, string> = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AM: 'Armenia',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BN: 'Brunei',
  BR: 'Brazil',
  BT: 'Bhutan',
  CA: 'Canada',
  CH: 'Switzerland',
  CL: 'Chile',
  CN: 'China',
  CO: 'Colombia',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DE: 'Germany',
  DK: 'Denmark',
  EE: 'Estonia',
  EG: 'Egypt',
  ES: 'Spain',
  FI: 'Finland',
  FR: 'France',
  GB: 'United Kingdom',
  GE: 'Georgia',
  GR: 'Greece',
  HK: 'Hong Kong',
  HR: 'Croatia',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JO: 'Jordan',
  JP: 'Japan',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KR: 'South Korea',
  KW: 'Kuwait',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LK: 'Sri Lanka',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'Macao',
  MV: 'Maldives',
  MX: 'Mexico',
  MY: 'Malaysia',
  NG: 'Nigeria',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  OM: 'Oman',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PS: 'Palestine',
  PT: 'Portugal',
  QA: 'Qatar',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  SA: 'Saudi Arabia',
  SE: 'Sweden',
  SG: 'Singapore',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SY: 'Syria',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TR: 'Turkey',
  TW: 'Taiwan',
  UA: 'Ukraine',
  US: 'United States',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VN: 'Vietnam',
  YE: 'Yemen',
  ZA: 'South Africa',
};

/** Apple/Google storefronts where 1,000 Stars is typically ~$25, not ~$20. */
export const HIGH_COST_STAR_MARKETS = [
  'GB',
  'DE',
  'AU',
  'AT',
  'BE',
  'CH',
  'DK',
  'FI',
  'FR',
  'IE',
  'IT',
  'LU',
  'NL',
  'NO',
  'NZ',
  'SE',
  'ES',
] as const;

/** Asia (incl. Middle East). India and Bangladesh are excluded — they pay catalog Stars. */
export const ASIAN_STAR_MARKETS = [
  'AE',
  'AF',
  'AM',
  'AZ',
  'BH',
  'BN',
  'BT',
  'CN',
  'CY',
  'GE',
  'HK',
  'ID',
  'IL',
  'IQ',
  'IR',
  'JO',
  'JP',
  'KG',
  'KH',
  'KR',
  'KW',
  'KZ',
  'LA',
  'LB',
  'LK',
  'MM',
  'MN',
  'MO',
  'MV',
  'MY',
  'NP',
  'OM',
  'PH',
  'PK',
  'PS',
  'QA',
  'SA',
  'SG',
  'SY',
  'TH',
  'TJ',
  'TL',
  'TM',
  'TR',
  'TW',
  'UZ',
  'VN',
  'YE',
] as const;

export function countryName(code: string): string {
  const key = code.trim().toUpperCase();
  return COUNTRY_NAMES[key] || key;
}

export function normalizeCountryCode(value: string): string {
  return value.trim().toUpperCase().replace(/[^A-Z]/g, '').slice(0, 2);
}
